### ISSUE TITLE
Add test to make sure TLS is really using TLS

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#113]
Add a test, perhaps using `openssl s_client -connect`, to verify that the TCP and websockets backends are really using TLS.

Ideally, also add a similar test for Receptor-level TLS (one Receptor user talking to another via netceptor.Conn), either by adding a TCP proxy and using openssl per above, or by using the control socket `connect`.

**Comment by squidboylan** [comment]
I'll open another issue for adding testing for receptor-level TLS
