### ISSUE TITLE
Allow remote work to specify remote control service TLS configuration

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#120]
Remote work submission and monitoring currently assumes that the remote node's control service will always be listening on the name `control` (see #15) and will never have TLS configured.  However, we want it to be possible to configure a node to enforce client certificate authentication before allowing access to the control service.

The difficulty here is that we might need to select different client TLS configurations based on which remote node we're connecting to.  Perhaps this could be a new section in the config file that takes a map of node names to TLS client configs.

**Comment by ghjm** [comment]
Note: The control socket `connect` command should also be able to use TLS-over-Receptor.

**Comment by squidboylan** [comment]
testing for this was added in https://github.com/project-receptor/receptor/pull/184
