### ISSUE TITLE
Unreachable for non-existing services

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#13]
We currently have a message type of MsgTypeReject which is used when a node refuses a connection from another node.  We should adapt this message type to include sending a per-connection reject when a stream connection is attempted to a service that doesn't have a listener on the remote side (similar to an ICMP Unreachable in tcp/ip).  Currently we get log errors on the remote side, but the dialer just has to sit there and eventually time out.

To do this we would need to:
* Add a data payload to the MsgTypeReject packets so we know _what_ is being rejected
* When we receive a MsgTypeReject (that isn't for a whole connection), look up the dialer socket that originated it, and flag it as being in an error state
* Return the error from anything blocked on that dialer, or any subsequent reads/writes to it

**Comment by squidboylan** [comment]
There's not really a good way to build an integration test around this, but it sounds like the traceroute capability relies on this so when we add tests for that that should add coverage for this, I'm closing this for now.
