### ISSUE TITLE
log-level: Debug  in config hangs on start

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#157]
`log-level: Debug` hangs, but
```yaml
- log-level:
     level: Debug
```
works fine

**Comment by ghjm** [comment]
This appears to be caused by the case of the level parameter.
```
- log-level:
    Level: Debug
```
also fails.

**Comment by ghjm** [comment]
It's not actually hanging - it's running normally, but with the log level set to Error, so it's not producing any output.  This is happening because cmdline is assigning the default value of Error even though a value was supplied.  I'm still looking into why.
