### ISSUE TITLE
Use build tags to make Receptor builds with limited feature sets

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#160]
If you are deploying Receptor in a highly secure environment, you may wish to make sure it cannot be used in ways you didn't intend.  For example, if you want to deploy leaf nodes that can only connect back to a central server and submit work, you might not want any listener backends.

Because the Receptor code is organized into self-contained files that include their own CLI objects etc, it would be quite easy to just exclude certain files from a build.  So we could, without much trouble, add build tags to these files, which would allow someone to run a `go build` that produces a binary with only the functionality they actually want.

**Comment by squidboylan** [comment]
I confirmed that when building with `no_udp_backend` there is no udp-listener help text and when configured to start a udp-listener the following error is returned:

```
Error loading config file: could not get config type for command udp-listener: unknown config type udp-listener
```
