### ISSUE TITLE
Handle kubernetes credentials in a secure manner

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#182]
Graham has a PR up that allows for passing in Kubernetes credentials at runtime, a requirement for the AWX / Tower use case of Receptor: project-receptor/receptor#172

There is a security concern regarding the implementation here:

> your k8s bearer token winds up in the Receptor status file, visible in work list, etc

**Comment by ghjm** [comment]
Between https://github.com/project-receptor/receptor/pull/172 and https://github.com/project-receptor/receptor/pull/199, I think this is as good as it's going to get.  The user has the following choices:

* You can send k8s credentials at runtime, and they are at least protected from viewing in `work list` etc.  They have to be saved to the work unit's status file, which is not encrypted at rest, but is 0600.
* You can save k8s credentials in the Receptor config file, which is also not encrypted by can be 0600.
* You can talk to a Receptor node already running in your k8s cluster, and use the incluster auth method.

**Comment by squidboylan** [comment]
I'm closing this, but we are unable to have any automated testing for this as we don't have access to a kubernetes cluster in our CI. I would like to have automated testing for this eventually though
