### ISSUE TITLE
Race condition in connection initialization logic

### ISSUE THREAD

**Issue by dehort** [ansible/receptor#188]
I believe I am running into a race condition in the connection initialization logic.  I am trying to use a golang program where I start 1000 go routines (in a burst) which connect to a websocket server.  The websocket server is using a new netceptor object per client connection.

The issue I am running into is that the client/sever cannot establish 1000 connections as some of the connections fail with the following error on the server side:

`ERROR 2020/09/24 16:09:27 Backend error: rejected connection with node node-970 because remote node no longer lists us as a connection
`
The server ends up closing the connection, which causes the client to log the following error message:

`ERROR 2020/09/24 16:09:27 Backend receiving error websocket: close 1006 (abnormal closure): unexpected EOF`

This appears to be happening because the server has progressed far enough to consider the client as connected (it gets into the "established" side of the protocol loop), however, the client has been slow enough that it has sent 2 initial connection messages (routingUpdate messages generated in the sendInitialConnectMessage() method) _before_ it has considered itself as connected ("established" is false).  Since the client does not consider itself as connected, it sends the routingUpdate messages with empty Connection entries.  The server, which considers itself as connected to the client (its processing in the "established" path of the protocol handling loop), checks for its node id in the second routingUpdate message that it receives from the client.  This check fails, which causes the server to log the "no longer lists us as a connection" error and it closes the connection.

**Comment by ghjm** [comment]
@dehort can you pull down the https://github.com/project-receptor/receptor/pull/194 branch and let me know if this fixes the error for you?

**Comment by dehort** [comment]
@ghjm #194 appears to have fixed this issue.  Thanks!
