### ISSUE TITLE
Duplicate nodes can exist

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#19]
Right now there is nothing preventing two nodes from joining the network with the same node ID, leading to who-knows-what routing confusion and destabilization of the network.

At first I thought we could do admission control so that a duplicate node ID gets rejected the same as if it wasn't in the allowed-connections list.  This turns out to be difficult.  First of all, in the current design it's surprisingly hard to tell if a given routing update is really a _new_ node, or an old node reconnecting after an outage.

Second, even if it could be done reliably, admissions control by a neighbor is not actually good enough.  If two same-named nodes join the network far apart from each other, and are accepted by their neighbors (who have, as yet, no reason to reject them), we still wind up with duplicate nodes.

Then I thought we could do duplicate node detection after the fact, by having nodes look for a situation where the same node ID exists at two different places on the network.  But there are problems with this as well.  First, how do you know if seeing a distant route to the same node ID means there's a duplicate, vs. the "real" node just having made a second connection to a distant peer?  Second, even if you do detect a duplicate, how do you know which one should shut down?

So, this turns out to be a difficult problem that will take some thought.

**Comment by ghjm** [comment]
It occurs to me that we might be able to use epochs for this.  Whenever a node restarts, it picks an epoch time that stays constant for the duration it is up.  I think that if a node ever receives a routing update with its own node ID but an earlier epoch, then this node is a duplicate and should shut down.

**Comment by squidboylan** [comment]
tested by unit tests and https://github.com/project-receptor/receptor/pull/258
