### ISSUE TITLE
Use TLS to validate node ID at protocol start

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#202]
Currently, backend mutual TLS allows us to validate that only permitted nodes are allowed on the mesh.  However, a node with a valid certificate can claim any node ID.  It would be preferable to have cryptographic assurances that a node can only use the node ID it has been assigned.

There are several possible implementations of this:

* Add a mapping of certificate fingerprints to node IDs in the config file for TCP and websockets backends, and check it at connection startup.
* At connection startup, exchange Receptor-level certificates as well, or make a test Receptor-level TLS connection, and verify that the client also has a Receptor-level client certificate with the correct node ID.
* Add node ID information to Receptor backend certificates, perhaps via the `subjectAltName` `otherName` mechanism.  If done right, this might allow a single certificate to function at both the backend and Receptor level.

**Comment by fosterseth** [comment]
This seems mostly complete. As of https://github.com/project-receptor/receptor/pull/201 receptor can required that connecting nodes have a valid client certificate, and that the nodeID of that client matches the subjectAltName in the provided cert.

I also confirmed that a single cert can be used for backend receptor connections, as well as at the receptor-level by utilizing the subjectAltName

for example, the following command will produce a cert that can be used to connect to the receptor mesh backend, and also any receptor-level connections (e.g. connecting to a control service)

`easyrsa --subject-alt-name="DNS:bar,DNS:localhost" sign-req client clientcertname`
