### ISSUE TITLE
Advertise things other than service listeners

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#21]
Workers defined by `work-command` do not listen on a service, and so they are not advertised to the network.  We should add an `Advertise()` method to Netceptor that adds an item to the advertisement broadcasts like `ListenAndAdvertise()`, but without needing a service listener.  This probably also implies changing the `ServiceAdvertisement` struct so that a recipient can tell what kind of non-service thing is being advertised.

**Comment by ryanpetrello** [comment]
@fosterseth @squidboylan I think this is technically "done" now?  Is there some mechanism you all are using for tracking these enhancements?

**Comment by ghjm** [comment]
I haven't looked at it too closely, but it seems like your PR is adding the list of work commands known on the node, to every service advertised on the node.  Seems like it would be better to have a single node-level advertisement with the work commands, rather than duplicating it for every service running on the node.

**Comment by ryanpetrello** [comment]
You're right, it piggybacks off the current per-service advertisement.  It might make more sense to modify this to be its own additional per-node advertisement at some point.

**Comment by shanemcd** [comment]
This is technically done. If someone wants to refactor how it's implemented, please open a separate issue to track the work.
