### ISSUE TITLE
Add a `params` field to `work-kubernetes`

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#230]
`work-command` and `work-kubernetes` should have roughly the same interface, but `work-kubernetes` is missing the `params` field that `work-command` has.

**Comment by shanemcd** [comment]
More worms for your can: currently, receptor uses the `command:` attribute when launching worker pods, which overrides the container's `entrypoint`, in docker / podman terminology. This is probably not what we want.

Perhaps we should change the receptor interface to allow for specifying `command` ("entrypoint") and `args` for the work-command and work-kubernetes plugins.

**Comment by squidboylan** [comment]
I think the `params` field for the work-command and work-kubernetes workers does what the `args` field would do (though as one string instead of a list of strings maybe). I'm gonna close this for now but if you think we should revisit this @shanemcd feel free to reach out and/or reopen this.
