### ISSUE TITLE
Kubernetes workers seem to return an error even though the pod completes

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#231]
there seems to be some race condition or set of conditions that are causing receptor to think a pod failed even though it succeeds.

```
{"State":3,"Detail":"Error creating pod: expected 1 container in pod but there were 0","StdoutSize":0,"WorkType":"echosleepshort","ExtraData":{"Image":"alpine","Command":"sh -c \"for i in `seq 1 5`; do echo $i;done\"","Params":"","KubeHost":"","KubeAPIPath":"","KubeNamespace":"default","KubeUsername":"","KubePassword":"","KubeBearerToken":"","KubeVerifyTLS":true,"KubeTLSCAData":"","PodName":"echosleepshort-gsxq8"}}
```

is the status of the job, however if i get the pod logs they look correct and `kubectl get pods echosleepshort-gsxq8` returns:

```
NAME                   READY   STATUS      RESTARTS   AGE
echosleepshort-gsxq8   0/1     Completed   0          21m
```

I'm not sure what is causing this, it seems to happen consistently with my `minikube_in_action` branch which modifies our existing work tests to be used with the kubernetes workers.

**Comment by ghjm** [comment]
This should be fixed by https://github.com/project-receptor/receptor/pull/242
