### ISSUE TITLE
Allow for passing in kubeconfig as runtime param

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#267]
Currently it is only possible to pass in individual config items: https://github.com/project-receptor/receptor/blob/820c4155becdb8839e3025469987ad00f4e68fe4/pkg/workceptor/kubernetes.go#L608-L618

**Comment by shanemcd** [comment]
I actually might retract this request. It's more secure if we never write this out to disk and therefore dont have to worry about cleaning it up.

**Comment by ghjm** [comment]
@shanemcd I'm not sure what you mean about writing it to disk.  Are you talking about the Tower code or the disk writes to the status file within Receptor?

**Comment by shanemcd** [comment]
@ghjm The former. Right now we write out a kubeconfig file and have to go to great lengths to make sure it's cleaned up. But your question raises the same concern. Will this status file always be cleaned up when the work is "released"?

**Comment by ghjm** [comment]
Yes, the status file is in a temporary directory specific to the unit of work, and the "release" operation deletes this directory.  (Of course this assumes "release" is called.  If a work unit is never released then its files are never deleted.)

**Comment by squidboylan** [comment]
@fosterseth  added testing for this as part of his PR, closing
