### ISSUE TITLE
Allow passing custom pod spec to work-kubernetes

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#268]
Folks are going to want control over the pod that receptor launches. Rather than trying to expose every possible knob as separate Receptor config options, a custom pod spec should be accepted at runtime.

**Comment by ghjm** [comment]
The challenges I see in this are:

* How to pass it in if statically configured.  Our scheme of CLI equivalency to the config file makes it difficult to just tack it on as a sub-key in the config yaml, so we need to decide if we want to refer to it as an external file, or extend the abilities of the `cmdline` library to accommodate this.
* How to store it in `kubeExtraData`.  This is potentially runtime data so it has to pass through the work unit's status file.  The `kubeExtraData` struct has to be JSON-serializable, so it's not clear that we can just add a member to the struct of type `corev1.PodSpec`.  (Although `PodSpec` has Marshal and Unmarshal methods so _maybe_ this will just work.)
* How, and whether, to deal with the desire to have some PodSpec parameters statically (and therefore securely) configured on a WorkType while other parameters are passed in at runtime.  Can you merge two PodSpecs?
* How to use it once we have it.  When executing a job, Receptor needs to be in control of the pod's lifecycle, have the ability to attach stdin/stdout to a known container within the pod, and maybe other things I've forgotten.  We would at least need to override some values in the PodSpec, or validate that it meets requirements, or something like that.  We also need to identify which container, if there are more than one, we ought to be interacting with for stdin/stdout of the job.

As long as we're looking at this there are a few other items we should deal with at the same time:

* Should we be launching pods directly or should we launch them via a k8s Job object?  The Job object gives failure behavior more closely aligned to what Receptor actually wants, most notably that work units, after any kind of failure, should never try to restart.  (For example if you ran half a playbook, and then there was a node failure and k8s restarted the pod, the worker output of half of one run plus the whole of the next won't be syntactically correct.)
* We currently have two different schemes for launching a pod and getting output back from it - the logger worker, which uses the same SPDY streams as `kubectl exec`, and the TCP worker, which has the worker make a non-k8s-managed TCP connection back to Receptor.  We should choose one and get rid of the other.
    * If we choose the TCP worker then we need to come up with a way to make it reconnectable (which likely involves a sidecar container or something like that, creating more difficulties if the user can supply an arbitrary PodSpec - do we just bolt our container on to the user's list or what?).  The TCP worker also has some janky code that picks the first seemingly-routable IP address for Receptor.
    * If we choose the logger worker then we need to satisfy ourselves that it won't break down with multi gigabyte output, since k8s is buffering this data.  Where is it stored?  Are we going to run the user out of disk space?  Does k8s performance degrade if output sizes are beyond a reasonable threshold?
* We currently have three different schemes for authenticating to k8s - in cluster, kubeconfig and individual parameters.  This could stand to be simplified.  If we get https://github.com/project-receptor/receptor/issues/267 done then maybe we just don't need the individual parameters option any more.

**Comment by shanemcd** [comment]
This is done.
