### ISSUE TITLE
Make it easier to turn off kubernetes tests

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#270]
Currently if you run `make ci` locally, the kubernetes tests run and, if you don't have a local k8s cluster set up, they (expectedly) fail.  There should be an easier way to run a local set of tests without needing to talk to a kubernetes instance.  Arguably, this should even be the default.

Also, maybe there should be a way for the kubernetes tests to run in a namespace other than "default".

**Comment by squidboylan** [comment]
k8s tests can now be skipped with the `SKIP_KUBE=1` environment variable. Tests cannot be run under a different namespace but i will close this and we can revisit it later.
