### ISSUE TITLE
Fix Netceptor Shutdown()

### ISSUE THREAD

**Issue by squidboylan** [ansible/receptor#28]
The Netceptor Shutdown function currently hangs, with non-blocking sends to the shutdown channels it doesnt hang, however it doesnt fully clean up all of the resources, particularly TCP ports, I think this is because one of our shutdown signals sends a signal to shutdown a TCP session, but we dont send a signal to close the port.

See https://github.com/project-receptor/receptor/pull/26 for some initial thoughts about this.

**Comment by ghjm** [comment]
One thing that's going on here is that the netceptor object defines a _single_ shutdown channel for the core protocol, but in the case of a listener, the core protocol may be running _many_ goroutines, one per incoming connection.  When the shutdown task sends a message to the channel, only one of these (or at most one) will receive it.

**Comment by ghjm** [comment]
Another thing that's going on is in the netceptor constructor, `make([]chan bool, 6)` only does a memory allocation of the slice - it does not initialize the individual channels.

**Comment by ghjm** [comment]
See https://github.com/project-receptor/receptor/pull/51
