### ISSUE TITLE
specify more than one dnsname in yaml

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#291]
e.g. this should be possible in cert-makereq

```
dnsname:
  - foo
  - foo2
```

**Comment by ghjm** [comment]
This actually should work already, the yaml loader has support for slices.  The problem is that it's unmarshaling this as a slice of `interface{}`s rather than a slice of strings.

**Comment by ghjm** [comment]
All the code to do this, including the type conversion, was already there.  We just never actually had a config file format that used slices like this before, so we never noticed it was silently failing and returning an empty array.  Unit tests definitely would have helped here.

**Comment by ghjm** [comment]
Fixed
