### ISSUE TITLE
Unable to share socket via AWS EFS mount 

### ISSUE THREAD

**Issue by ethemcemozkan** [ansible/receptor#314]
As part of AWX environment, I am trying to share receptor socket via AWS EFS mount. EFS volume directly attached to ECS task. We use the same setup to share our Redis socket.

But unlike Redis, Receptor fails with 'Error: error opening Unix socket: could not acquire lock on socket file: bad file descriptor' error message. 

I can see receptor.sock.lock file is created. But not the .socket file.

**Comment by shanemcd** [comment]
Can you describe your topology a bit more? What's the use case for using an EFS volume in your AWX deployment?

**Comment by ethemcemozkan** [comment]
@shanemcd We have 4 containers running for our AWX environment. These are awx-web, awx-task, redis and receptor. 
AWX containers require receptor and redis sockets. In every container, folders that contain these sockets are mounted to the respective EFS file system directory. This way we can share sockets between containers.

Sadly we have to share sockets because AWX currently only supports sockets for receptor.

**Comment by shanemcd** [comment]
@ethemcemozkan Typically all of those containers live within the same pod, which are guaranteed to land on the same host, so we share the sockets via an emptyDir. It sounds like you are trying to craft your own topology? Just trying to better understand your situation.

**Comment by ethemcemozkan** [comment]
@shanemcd Yes, we have our own topology inspired by AWX docker-compose setup. 
We are using AWS ECS with Fargate. So only way for us to share directories between containers is to use EFS(NFS mounted).
I also tested locally. If I start a receptor container with bind mount to host folder which mounted to NFS it fails with the same error.(Receptor is configured to place the socket in this folder). I don't know why but socket creation fails when i try to place it in NFS mounted folder.

**Comment by wenottingham** [comment]
>  don't know why but socket creation fails when i try to place it in NFS mounted folder.

Because that's not a thing in Linux - never has been.
Your topology will not work. I'd suggest using kubernetes rather than trying to stretch the docker-compose dev env over mulitple m achines.
