### ISSUE TITLE
work release <unitid> results in panic

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/receptor#317]
### Steps to reproduce
* Start a receptor worker node `cmd/cmd --config local.yml`
* Submit work through the local node. Note, we are going to pick a node that doesn't exist just so the work hangs out. `RECEPTORCTL_SOCKET=/tmp/receptor.sock receptorctl work submit --node foobar --no-payload work` Note the `Unit ID:` returned.
* Shutdown the receptor node `Ctrl+C`
* Start the receptor node back up `cmd/cmd --config local.yml`
* Release the work previously started `receptorctl work release <Unit ID>`

### Expected
`Released: ('z6m3Tqtl',)`

### Actual
`<Unit ID>: ERROR: Expecting value: line 1 column 1 (char 0)`

Panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13d666e]

goroutine 46 [running]:
github.com/project-receptor/receptor/pkg/utils.(*JobContext).Cancel(...)
        /home/meyers/ansible/receptor/pkg/utils/job_context.go:92
github.com/project-receptor/receptor/pkg/workceptor.(*remoteUnit).cancelOrRelease(0xc0004968f0, 0x410001, 0xc0002655c0, 0x1750c88)
        /home/meyers/ansible/receptor/pkg/workceptor/remote_work.go:554 +0x1ee
github.com/project-receptor/receptor/pkg/workceptor.(*remoteUnit).Release(0xc0004968f0, 0xc000495400, 0x8, 0x18954c0)
        /home/meyers/ansible/receptor/pkg/workceptor/remote_work.go:580 +0x39
github.com/project-receptor/receptor/pkg/workceptor.(*workceptorCommand).ControlFunc(0xc0001117a0, 0xc0002f9b00, 0x187df60, 0xc0004a48f0, 0x0, 0x0, 0x0)
        /home/meyers/ansible/receptor/pkg/workceptor/controlsvc.go:276 +0x41b
github.com/project-receptor/receptor/pkg/controlsvc.(*Server).RunControlSession(0xc000375b30, 0x188be80, 0xc00038a090)
        /home/meyers/ansible/receptor/pkg/controlsvc/controlsvc.go:210 +0xaa2
github.com/project-receptor/receptor/pkg/controlsvc.(*Server).RunControlSvc.func2.1(0x188be80, 0xc00038a090, 0xc00038c020, 0xc000375b30)
        /home/meyers/ansible/receptor/pkg/controlsvc/controlsvc.go:343 +0x66
created by github.com/project-receptor/receptor/pkg/controlsvc.(*Server).RunControlSvc.func2
        /home/meyers/ansible/receptor/pkg/controlsvc/controlsvc.go:320 +0x5e
```

```
# local.yml
---
- log-level: debug
- control-service:
    service: control
    filename: /tmp/receptor.sock
- local-only:
- work-command:
    worktype: worker
    command: ansible-runner
    params: worker
- node:
    id: foo
```

### Extra Info
Interesting that calling work release on a directory that does NOT exist in `/tmp/receptor/foo/` is handled OK. 

Related changes https://github.com/ansible/receptor/pull/235 These changes also result in receptor failing to resume work for nodes it never saw, when restarted.

**Comment by amolgautam25** [comment]
Related PR : https://github.com/ansible/receptor/pull/336

**Comment by amolgautam25** [comment]
The panic was caused by accessing an invalid pointer , in this case `nil` pointer.

The exact code responsible for this was the following : 
```
func (rw *remoteUnit) cancelOrRelease(release bool, force bool) error {
.
rw.topJC.Cancel() <-------
rw.topJC.Wait()
.}
```

The object ```rw.topJC.Cancel()``` was ```nil``` in this case , and hence the invalid dereference. 

Fix: 

When the node ```foo``` is restarting , check if the previous job on remote node was started or not. If it was not started , set  ```topJC``` value to ```nil```

While the job is being released , the following check is used to bypass nil pointer dereference :
```
if rw.topJC != nil {
rw.topJC.Cancel()
rw.topJC.Wait()
}
```

**Comment by fosterseth** [comment]
fixed
