### ISSUE TITLE
Check for and reject negative path costs

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#32]
I think in the current implementation, you could do `--tcp-peer cost=-1.0` and cause the route calculation to blow up (for example, it might loop infinitely, trying to find the path that maximizes the number of times the packet traverses this path, because every traversal reduces the cost).

Negative path costs should be checked for at config load time and rejected.

**Comment by squidboylan** [comment]
Added automated testing for this in https://github.com/project-receptor/receptor/pull/98
