### ISSUE TITLE
Write Documentation for Live Reload feature

### ISSUE THREAD

**Issue by amolgautam25** [ansible/receptor#355]
Receptor documentation for receptor reload feature

Complexity estimate : easy
Time Estimate : 1 sprint

Acceptance criteria
- Example that has a configuration file with peer lists, starting receptor with these backends, making the change to the config file, and the command the issue the reload so that receptor is aware of changes 
- Have a dev from a separate pod review the documentation, proof-read and carry out example snippets
- Published to read-the-docs

**Comment by fosterseth** [comment]
let's track documentation development here https://github.com/ansible/receptor/issues/18

**Comment by fosterseth** [comment]
https://receptor.readthedocs.io/en/latest/interacting_with_nodes.html#reload
