### ISSUE TITLE
Restrict naming of nodes and services.

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#396]
Hey all. I noticed that the names of services are limities to 8 Bytes, not characters as documented. (https://github.com/ansible/receptor/blob/ac0a72f9a18344ef9c853fcec0d0d4f5d4a2070b/pkg/netceptor/conn.go#L40). 
While that is an easy fix I was wondering if we should lock down names even more. I believe " " and "  " would be legitimate distinguished names and also my all time favorite service name "ʕ •ᴥ•ʔ" is allowed. While I am very much in favour of keeping 
"ʕ •`ᴥ•´ʔ", I would like to discuss if we should restrict the rest

**Comment by wenottingham** [comment]
If there are no technical reasons that prevent us naming a service 🐕➕🌈, we should allow it.

**Comment by shanemcd** [comment]
@ghjm what say you?

**Comment by ghjm** [comment]
Service names are limited to 8 bytes because they are part of a fixed length protocol header, for speed and reliability, not to mention the whole scheme with HighwayHash.  If you want to make this variable length you can, but it would be a major change to the whole underpinnings of netceptor.

**Comment by eqrx** [comment]
@wenottingham I name my receptor nodes something like "ʕ •ᴥ•ʔ "... that works :D
Thanks for explaining @ghjm, then let me update the doc to state it bytes and not runes :)

**Comment by ghjm** [comment]
Yes, other than the length I don't think there's any problem with using Unicode.  Name your service 🐉⚽ if you like.  As long as the utf-8 encoding is 8 bytes or less.
