### ISSUE TITLE
Make Makefile a bit more installation independent 

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#399]
When I run `make` to just build the Go part of receptor on a system with a non rpm based distro and not pip/wheel installed this happens:

```
$ make
WARNING: The wheel package is not available.
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
make: rpm: No such file or directory
CGO_ENABLED=0 go build -o receptor -ldflags "-X 'github.com/ansible/receptor/pkg/version.Version=0.9.8.dev132-0.git20210827.ac0a72f'"  ./cmd/receptor-cl
```
I would like to reduce the noise here!

**Comment by thenets** [comment]
If you want to use the `Makefile` to generate the `receptor` binary and the wheel for `receptorctl`, I created a new Makefile:
- https://github.com/ansible/receptor/blob/devel/tests/Makefile

Type `make` and that's it. The only requirement is `docker` installed, used to have a controlled environment.

I made this Makefile for the exact same reason. I got errors and inconsistencies when I was trying to build and the project.
