### ISSUE TITLE
PacketConn of netceptor silently drops message data if read buffer is to small

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#400]
Is this expected?
If I set my read buffer to 16 bytes length and the message is 32 long, I get no indication that something got dropped. I understand that the interface should look like `net.PacketConn` but shouldn't we provide a way to just get the data slice without the copy?
https://github.com/ansible/receptor/blob/ac0a72f9a18344ef9c853fcec0d0d4f5d4a2070b/pkg/netceptor/packetconn.go#L144

**Comment by shanemcd** [comment]
Not sure if we should be silently dropping them, but I'm assuming it's because we know we need enough bytes to reconstruct a MessageData object. Curious if @ghjm has any more insight here.

**Comment by ghjm** [comment]
If I remember correctly, the reason for the copy is that we only have a pointer to the `messageData` object, which gets reused in the main netceptor loop to avoid needing to do a dynamic memory allocation on every packet.  Or something like that.  So the copy is because we don't trust the recipient to have a pointer to our internal data structure.

I agree it's a bit odd that you can't tell if you've lost part of a packet, but I think this is just how `PacketConn` works in Go?  If there's some functionality that `net.UDPConn` provides that we don't, then we should add it.  The goal is to look just like any other normal Go datagram connection.

**Comment by eqrx** [comment]
Hey @ghjm! I looked more into the network stack of linux and how memory passing between kernel and userspace works. You are totally right that this is how it works. Thanks for clarifying!

(FYI follows) 
The linux [recvfrom](https://man7.org/linux/man-pages/man2/recv.2.html) just shoves as much of the datagram into the given buffer as possible. So this behavior is not even Go sprecific :o One would need to use `recvmsg` to get the indication that the message was truncated. 

I also noticed that while UDP allows 65535 (2^16) bytes as the maximum payload length (which receptor supports by default), the payload may only be as large as the interface MTU minus the header IP and UDP header sizes. The default MTU generally is 1500 bytes ...

**Comment by ghjm** [comment]
UDP does support fragmentation, so a UDP message may be larger than the MTU if "don't fragment" is not set.  It would be a nice addition to the Receptor UDP backend to try to avoid fragmentation by doing path MTU discovery per peer.  It would also be nice to have a thread pool of transmitters/receivers.  Currently Receptor performs better using the TCP backend than UDP over a clean link, where the opposite should be the case, if it was tuned a bit better.  However, I'm not sure how many people actually care about the Receptor UDP backend.

**Comment by eqrx** [comment]
I overlooked fragmentation, thanks for the insight. Let me open an issue for your suggestions.

Yeah, I am not quiet sure which backend is the default people tend to use. I was assuming it would be UDP since a QUIC session is layered over the backends transport ... and QUIC over TCP seems redundant. Let me investigate that

**Comment by ghjm** [comment]
QUIC over TCP is still a lot better than TCP over TCP, though.  QUIC is designed to be resistant to TCP meltdown.  Though I agree that a well tuned UDP implementation would be best.

There's also some room for improvement on the Receptor TCP backend.  It breaks up the stream into "packets" using length descriptors.  It might be possible to eke out a few percentage points of efficiency by opening multiple TCP streams and perhaps reserving one for small packets, or using a separate stream for routing updates.  But I'm not at all sure that the gains would be worth the added complexity.
