### ISSUE TITLE
Mesh installer add firewall rules

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#403]
- Adding firewall on control  nodes to block traffic targeting own control service from any other node
- Ask mesh code pod whether it is okay to block all traffic (status, work submit commands)  from one hybrid node to another hybrid node

**Comment by AlanCoding** [comment]
:+1: should be okay to block status / work submit commands from one hybrid node to another. It should be okay to block those commands from _any_ node other than itself for hybrid / control nodes.

I was previously thinking I might use the mesh for the health check endpoint for hybrid nodes. However, that had other complications and I re-designed it to use the postgres message bus and database polls.

**Comment by amolgautam25** [comment]
PR for this issue : https://github.com/ansible/automation-platform-collection/pull/158

**Comment by yagomarques** [comment]
we've already tested this functionality, it's working.
