### ISSUE TITLE
RFE: add option to output json instead of pretty output from "receptorctl status"

### ISSUE THREAD

**Issue by kdelee** [ansible/receptor#413]
I would like to be able to do something like `receptorctl status --json` or `receptorctl status -o json` so I can parse the output

This will help us automating validation downstream that expected changes were applied by the installer that sets all the receptor config files in place. We can configure the installer to set up peers in a certain way, run the installer, and then check the connections via `receptorctl status -o json` and parse the output to find the parts we are interested in.

**Comment by kdelee** [comment]
This is merged, ready to test https://github.com/ansible/receptor/blob/7cb98c7212534f2a4f2b9e055daff733a823de4c/receptorctl/receptorctl/cli.py#L53

https://github.com/ansible/receptor/commit/1d311b97c7ca260c254d10625ec2fc13c15e2548

**Comment by thenets** [comment]
Done in this PR:
- https://github.com/ansible/receptor/pull/445

Waiting to be approved.
