### ISSUE TITLE
Name version tags so Go understands them

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#415]
We currently name our tags `MAJOR.MINOR.PATCH`. But go tooling needs (see https://go.dev/blog/publishing-go-modules) another name to understand it `vMAJOR.MINOR.PATCH`. We should change the tag naming scheme.

Or else this happens: https://pkg.go.dev/github.com/ansible/receptor?tab=versions

**Comment by shanemcd** [comment]
Latest tag adheres to this format. Thank you for bringing this up.
