### ISSUE TITLE
Verification of nodeID to cert before joining mesh

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#420]
- Currently nodes can "lie" about their nodeID (nodeID in config doesn't have to match what is in cert)

- Verification takes place as control service level, but not to join mesh

- This feature will ensure nodes joining mesh have a nodeID that matches what is in their cert

Acceptance Criteria:

- Try to set up a receptor node with nodeID "foo2" but your cert says you are "foo". Should not be able to join, and this node should not be on the routing table when issuing a "status" command

Time estimate: 1 sprint

**Comment by alisondudiak** [comment]
might be related - https://github.com/ansible/receptor/pull/553

**Comment by sarabrajsingh** [comment]
reproducer:

1. use `tower-packaging@devel` to install at least a 2-node cluster, compromising of one control and one execution node (normal path forward). this will install a cluster with the changes from #553.

#### scenario 1 - bad cert (wrong CN, wrong SAN) given to a node that was in the mesh

2. after installation, leverage the receptor self-signed CA located in `/etc/receptor/tls/ca/mesh-CA.crt` to create a new `csr`. the idea here is to generate a cert with a bad CN, bad SAN, and incorrect originating IPs. 
```bash
receptor --cert-makereq commonname=foobar bits=4096 nodeid=foobar outreq=/etc/receptor/tls/foobar.csr outkey=/etc/receptor/tls/foobar.key ipaddress=127.0.0.1 ipaddress=127.0.0.1
```
3. leverage receptors' self-signed CA to sign the CSR and generate a certificate for consumption
```bash
receptor --cert-signreq verify=yes cacert=/etc/receptor/tls/ca/mesh-CA.crt cakey=/etc/receptor/tls/ca/mesh-CA.key req=/etc/receptor/tls/foobar.csr outcert=/etc/receptor/tls/foobar.crt notafter="2031-12-28T00:03:51-05:00"
```
4. copy over `/etc/receptor/tls/foobar.crt` and `/etc/receptor/tls/foobar.key` to an execution node. note the IP address of the execution node (in my case, it's `192.168.56.104`)
5. modify the `/etc/receptor/receptor.conf` file on the execution node to reference the new fudged cert. namely, edit the `tls-server` and `tls-client` sections
```yaml
# TLS
- tls-server:
    name: tls_server
    cert: /etc/receptor/tls/foobar.crt
    key: /etc/receptor/tls/foobar.key
    clientcas: /etc/receptor/tls/ca/mesh-CA.crt
    requireclientcert: true

- tls-client:
    name: tls_client
    cert: /etc/receptor/tls/foobar.crt
    key: /etc/receptor/tls/foobar.key
    rootcas: /etc/receptor/tls/ca/mesh-CA.crt
    insecureskipverify: false
```
6. restart the receptor systemd service on the execution node
```bash
systemctl restart receptor.service
```
7. examine the receptor logs at `/var/log/receptor/receptor.log` on the execution node
##### should see something like this
```bash
ERROR 2022/02/24 11:43:37 Backend receiving error remote error: tls: bad certificate
ERROR 2022/02/24 11:43:37 Backend sending error remote error: tls: bad certificate
```
8. examine the output of `receptorctl` on the execution node
```bash
[root@rhel-vm-2 /]# receptorctl --socket /run/awx-receptor/receptor.sock status
Node ID: 192.168.56.104
Version: 1.2.0
System CPU Count: 3
System Memory MiB: 3928

Node         Service   Type       Last Seen             Tags
192.168.56.104 control   StreamTLS  2022-02-24 11:44:16   {'type': 'Control Service'}

Node         Secure Work Types
192.168.56.104 ansible-runner
[root@rhel-vm-2 /]# 
```
we can see here that the execution node hasn't joined the mesh, with tls bad cert artifacts in the receptor log

9. examine the output of `receptorctl` on the control node
```bash
[root@rhel-vm-1 /]# receptorctl --socket /run/awx-receptor/receptor.sock status
Node ID: 192.168.56.103
Version: 1.2.0
System CPU Count: 3
System Memory MiB: 3928

Known Node     Known Connections
192.168.56.103 
192.168.56.104 

Node           Service   Type       Last Seen             Tags
192.168.56.103 control   StreamTLS  2022-02-24 11:45:48   {'type': 'Control Service'}
192.168.56.104 control   StreamTLS  2022-02-24 11:43:02   {'type': 'Control Service'}

Node           Secure Work Types
192.168.56.103 local, kubernetes-runtime-auth, kubernetes-incluster-auth
192.168.56.104 ansible-runner
```
the control node is still aware of a peer it lost. so lets check the logs

10. examine the output of `/var/log/receptor/receptor.log` on the control node
```bash
WARNING 2022/02/24 11:40:11 Backend connection failed (will retry): x509: certificate is valid for 127.0.0.1, 127.0.0.1, not 192.168.56.104
WARNING 2022/02/24 11:40:31 Backend connection failed (will retry): x509: certificate is valid for 127.0.0.1, 127.0.0.1, not 192.168.56.104
WARNING 2022/02/24 11:40:51 Backend connection failed (will retry): x509: certificate is valid for 127.0.0.1, 127.0.0.1, not 192.168.56.104
```
11. issue a `systemctl restart receptor.service` on the control node and re-examine `receptorctl status`
```bash
[root@rhel-vm-1 /]# receptorctl --socket /run/awx-receptor/receptor.sock status
Node ID: 192.168.56.103
Version: 1.2.0
System CPU Count: 3
System Memory MiB: 3928

Node         Service   Type       Last Seen             Tags
192.168.56.103 control   StreamTLS  2022-02-24 11:47:23   {'type': 'Control Service'}

Node         Secure Work Types
192.168.56.103 local, kubernetes-runtime-auth, kubernetes-incluster-auth
```
the control node no longer recognizes `192.168.56.104` with a bad cert. i think we can close https://github.com/ansible/receptor/pull/482 now.

#### scenario 2 - good cert on the execution node, bad nodeID in the `receptor.conf` file
11. restore the `receptor.conf` file back to stock on the execution node and rejoin the mesh. issue a `systemctl restart receptor.service` after modifying the `receptor.conf` file
```bash
[root@rhel-vm-2 /]# receptorctl --socket /run/awx-receptor/receptor.sock status
Node ID: 192.168.56.104
Version: 1.2.0
System CPU Count: 3
System Memory MiB: 3928

Connection     Cost
192.168.56.103 1

Known Node     Known Connections
192.168.56.103 192.168.56.104: 1 
192.168.56.104 192.168.56.103: 1 

Route          Via
192.168.56.103 192.168.56.103

Node           Service   Type       Last Seen             Tags
192.168.56.104 control   StreamTLS  2022-02-24 11:52:09   {'type': 'Control Service'}
192.168.56.103 control   StreamTLS  2022-02-24 11:51:24   {'type': 'Control Service'}

Node           Secure Work Types
192.168.56.104 ansible-runner
192.168.56.103 local, kubernetes-runtime-auth, kubernetes-incluster-auth
```
12. fudge the nodeID in `receptor.conf` on the execution node, issue a `systemctl restart receptor.service` on the execution node and examine `receptorctl status`
##### receptor.conf
```yaml
---
- node:
    id: foobar
```
```bash
[root@rhel-vm-2 /]# receptorctl --socket /run/awx-receptor/receptor.sock status
Node ID: foobar
Version: 1.2.0
System CPU Count: 3
System Memory MiB: 3928

Connection     Cost
192.168.56.103 1

Known Node     Known Connections
192.168.56.103 foobar: 1 
foobar         192.168.56.103: 1 

Route          Via
192.168.56.103 192.168.56.103

Node           Service   Type       Last Seen             Tags
foobar         control   StreamTLS  2022-02-24 12:14:09   {'type': 'Control Service'}

Node           Secure Work Types
foobar         ansible-runner
```
these are the logs from the control node
```bash
[root@rhel-vm-1 ~]# tail -f /var/log/receptor/receptor.log
INFO 2022/02/24 12:13:49    192.168.56.103: 
INFO 2022/02/24 12:13:49    192.168.56.104: 
INFO 2022/02/24 12:13:49 Routing Table:
INFO 2022/02/24 12:13:54 Connection established with foobar
INFO 2022/02/24 12:13:54 Known Connections:
INFO 2022/02/24 12:13:54    192.168.56.103: foobar(1.00) 
INFO 2022/02/24 12:13:54    192.168.56.104: 
INFO 2022/02/24 12:13:54    foobar: 192.168.56.103(1.00) 
INFO 2022/02/24 12:13:54 Routing Table:
INFO 2022/02/24 12:13:54    foobar via foobar
```
so a `nodeID` that doesn't match the `CN` or `SAN` of the certs its using to connect to the mesh. need to fix this

**Comment by sarabrajsingh** [comment]
MVP:

1. at bootstrap time - look at TLS certs (if specified), pull out receptorName from SAN/CN/OIDs, check against receptorName from config file. If a receptorName/otherName is found in the cert, then verify against `MainInstance.Neteceptor.nodeID` in config file. put this in `tlsconfig.go`

- [x] check CN of cert, search for match with nodeID from configFile
- [x] check SAN(s) of the cert, search for a match with nodeID from configFile
- [x] check OID(s) of the cert, search for a match with nodeID from configFile

2. add unit tests for step1 using the receptor cert generation utility, for the aforementioned checks above

Long Term:

1. start thinking about the best way to leverage the Dialer/Listener TCP pattern for the backend connections to verify an incoming client's nodeID, with whats provided in the client certs.

**Comment by thenets** [comment]
This is already validated, right?
Is this test change here?
- https://github.com/ansible/receptor/pull/578

@sarabrajsingh @fosterseth

**Comment by sarabrajsingh** [comment]
@thenets sorry about the workflow set to `done`. no it has not been tested, i put the issue back to `needs test`.

**Comment by thenets** [comment]
@sarabrajsingh oh, in that case, can you help me to set up a manual test? Then I can create the test automation.

**Comment by thenets** [comment]
Reproduced manually successfully.
I'll close this and open a PR for automated test.
