### ISSUE TITLE
add verification to work cancel and work release

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#428]
if verifySignature is set to true, only authorized nodes are able to start that work unit. However, it is still the case that any node on the mesh could cancel and release that work unit.

We should extend the work signing feature to only allow authorized nodes to cancel those work units.

**Comment by chrismeyersfsu** [comment]
@fosterseth should this be in `needs_test` ?

**Comment by fosterseth** [comment]
https://github.com/ansible/receptor/pull/430

**Comment by thenets** [comment]
`receptorctl` is failing. I added in the PR the error message:
- https://github.com/ansible/receptor/pull/468

**Comment by shanemcd** [comment]
Why was this moved back to needs_devel?

**Comment by thenets** [comment]
@shanemcd the test that I created `test_work_signed_expect_block` is failing:
- https://github.com/ansible/receptor/pull/468

We need to fix the code. That's why I moved back to `needs_devel`.

**Comment by thenets** [comment]
@shanemcd I need to have that PR merged. I talked to @fosterseth and we decided to comment the test that was failing until the patch that fixes the issue.

Can you help us to review and merge it? We have many PR already open.

**Comment by fosterseth** [comment]
implemented here https://github.com/ansible/receptor/pull/430
