### ISSUE TITLE
make sys.exit in receptorctl more consistent

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#431]
client errors should exit with error code 1. These would include incorrect parameters, command line errors, etc.

receptor related errors should exit with code 2+. We can devise some reasonable scheme, or perhaps the error code is specific to the command that was run. For example, in `reload`, error code 3 means the configuration file is not-reloadable, and a restart is needed. Error code 4 means something is wrong with the configuration file.

**Comment by thenets** [comment]
@tiagodread I made a major refactor and now is possible to create tests for that kind of case very easily:
- https://github.com/ansible/receptor/pull/447

Ping me later if you want to make this together.

**Comment by tiagodread** [comment]
@fosterseth 

- **work.results**
running on terminal:
```
$ receptorctl --socket /tmp/receptorctltest/node1.sock work results
Error: Missing parameter: unit_id

$ echo $?                                                          
1
```
 however, exit_code is 2 and stdout is different is this desired?
![image](https://user-images.githubusercontent.com/12464858/138771284-880e9a9d-8f28-4340-b848-e70089afed63.png)

Same thing happening for `work.submit`
