### ISSUE TITLE
receptor waits one second before forcefully killing cmd process, may need to wait longer for some processes to clean-up

### ISSUE THREAD

**Issue by jladdjr** [ansible/receptor#434]
When I call `work cancel` on a receptor work item that is executing an ansible-runner process, the runner process is cleaned up, but the container that it spawned is left behind. We suspect that runner may just not have enough time to cleanup and exit.

PR for extend waiting time to ten seconds:
https://github.com/ansible/receptor/pull/433

**Comment by AlanCoding** [comment]
Add to this, a comment by @chrismeyersfsu, receptor should kill the _process group_ not just the process.

**Comment by jladdjr** [comment]
I wrote up the minor tweak to extend the wait time. As @AlanCoding mentioned though, there's other work being discussed re: cleaning up the parent process group.

**Comment by chrismeyersfsu** [comment]
related to https://github.com/ansible/receptor/pull/440

**Comment by jladdjr** [comment]
dropping `in_progress` label as this got moved over to `needs_test`

**Comment by jladdjr** [comment]
@thenets - believe that this could be considered verified as part of https://github.com/ansible/tower/issues/5310

**Comment by thenets** [comment]
I believe this can be closed cause I already test the receptor behavior from the job reaping tests on AWX.
Looks like the receptor is allowing the container to be cleaned up as expected.
