### ISSUE TITLE
cleanup potential go leaks

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#436]
In a few places I've seen the following pattern
``` golang
doneChan := make(chan bool)

go func() {
      waitOnSomething()
      doneChan <- true // this send is blocking and requires something to read from doneChan
}

select {
     case <- doneChan: // this reads from doneChan, so the go routine returns cleanly
     case <- SomeOtherChan:
          // we never read from doneChan, so go routine never returns and is a leak
           return
}
```

One solution is to use a buffered channel, `doneChan := make(chan bool, 1)`

With a buffered channel, the send will only block if the capacity is 0 (before it sends). Since we set up the channel with capacity 1, the sender won't block and will return.

see https://stackoverflow.com/questions/38090545/are-goroutines-garbage-collected-together-with-their-channels

We should comb the code base for this kind of pattern and make sure we are either using buffered channels (where appropriate, sometimes you want blocked sends on channels), or make sure the channels are read somewhere else.

**Comment by eqrx** [comment]
Hey @fosterseth. I would suggest using a `chan struct{}` and simply close it when the routine is done. See https://go.dev/blog/pipelines for the "offical" way like the `context` package does it.

```go

done := make(chan struct{})
go func() {
  defer close(done)
  [...]
} ()

select {
  case <- done:
  [...]
}
```

This shows what is desired more clearly: We do not care about the payload in the channel and close it when the routine is done.

anyway, thanks for picking that up :)

**Comment by fosterseth** [comment]
too open-ended of an issue, closing.

**Comment by eqrx** [comment]
Is it really open ended though? Routines are not correctly handled all across the project and that is a lot of work (that is finite).... but it needs to be addressed :(
