### ISSUE TITLE
Cannot cancel or release local work unit when it has a remote work unit that cannot be found

### ISSUE THREAD

**Issue by kdelee** [ansible/receptor#451]
We have a work unit in `work list` that has a remote work unit associated, but on the remote node the work unit no longer exists.
```
{'2z1oqEvu': {'Detail': 'exit status 0',
              'ExtraData': {'Expiration': '2021-10-19T07:46:55.310851834Z',
                            'LocalCancelled': True,
                            'LocalReleased': True,
                            'RemoteNode': '158.176.173.229',
                            'RemoteParams': {'params': '--worker-info'},
                            'RemoteStarted': True,
                            'RemoteUnitID': 'i4GERNa2',
                            'RemoteWorkType': 'ansible-runner',
                            'SignWork': True,
                            'TLSClient': 'tls_client'},
              'State': 2,
              'StateName': 'Succeeded',
              'StdoutSize': 122,
              'WorkType': 'remote'}
```

We want to cancel/release this work. Canceling not working maybe makes sense because it can't find it remotely and it is maybe already `Succeeded`.

The remote work unit is gone, it is not present in the remote node `work list`
It additionally does not have any data in `/tmp/receptor` on the remote node.

Running `release` or `release --force`  does not work.

Just running `release` results in an error 
```
receptorctl --socket /var/run/awx-receptor/receptor.sock work release 2z1oqEvu
Released:
2z1oqEvu: ERROR: error cancelling remote unit:  unknown work unit i4GERNa2
```

Running `release --force` hangs and does not accomplish releasing the work.
```
receptorctl --socket /var/run/awx-receptor/receptor.sock work release 2z1oqEvu
Released:
```

**Comment by kdelee** [comment]
Here's another one, that eith both `work release` and `work release --force` is not going away
```
 'q4fcgHjS': {'Detail': 'exit status 0',
              'ExtraData': {'Expiration': '2021-10-20T15:36:24.271651069Z',
                            'LocalCancelled': True,
                            'LocalReleased': True,
                            'RemoteNode': '158.176.173.229',
                            'RemoteParams': {'params': '--worker-info'},
                            'RemoteStarted': True,
                            'RemoteUnitID': '0W3IQlcG',
                            'RemoteWorkType': 'ansible-runner',
                            'SignWork': True,
                            'TLSClient': 'tls_client'},
              'State': 2,
              'StateName': 'Succeeded',
              'StdoutSize': 122,
              'WorkType': 'remote'}
```
and it just hangs w/ no error

**Comment by shanemcd** [comment]
Ping @fosterseth

**Comment by chrismeyersfsu** [comment]
This boils down to semantics. Controller is going to need to force cancel/stop/kill. I can't care so much if it's a new flag to capture this behavior change with still being backwards compat or if we just change `work release` or `work cancel` (without any flags) to be able to kill/stop this case.

**Comment by fosterseth** [comment]
We need to re-demonstrate that this is a bug -- a lot has changed in the code since this issue and it's possible this issue is no longer relevant. Locally, when I test `work cancel` or release on non-existent work ids I do get a proper error return.

**Comment by shanemcd** [comment]
This looks very similar to an issue that a customer reported. We sent them a newer version of Receptor and they said it fixed their issue. If you see this again please reopen.
