### ISSUE TITLE
Refactor netceptor

### ISSUE THREAD

**Issue by eqrx** [ansible/receptor#453]
The netceptor struct somehow managed to amass seven individual locks/mutexes which is a pretty strong indicator to me that it needs to be broken down in smaller pieces. On one side this would take a core component on receptor and possibly cause a lot of pain regarding rewrites and tests but on the other side, it decouples all that functionality and makes it more testable.

**Comment by ghjm** [comment]
This is certainly true.  Also, at least some of the mutexes could be replaced by single-threaded goroutines that respond on channels, which would make a lot of this more readable and less risky to work on.  I'd definitely be looking at this if I still worked there.

**Comment by eqrx** [comment]
@ghjm thank for the comment and you time :)
