### ISSUE TITLE
Add MaxIdleTimeout to quic connections

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#461]
We should explore adding this parameter when establishing quic connections

https://pkg.go.dev/github.com/lucas-clemente/quic-go#Config

This might help cleanup left over connections that never received an explicit "hangup" signal

**Comment by john-westcott-iv** [comment]
From the docs and looking at the source code it looks like the default MaxIdleTimeout is set to 30 sec. Do we want to make this configurable or change this?

**Comment by fosterseth** [comment]
I think it can be configurable when initiating a netceptor object, and provide a default value at the top of netceptor.go. I don't think this needs to be in the receptor.conf. I think a 60 second timeout would probably be fine.

I think a simple test would be to setup 2 netceptor objects and establish a quic connection with a timeout of say, 10 seconds. Send some data over the connection, then let it sit for 10 seconds. Try to send more data and assert failure.

The setup would be similar to `examples/net.go`
