### ISSUE TITLE
remove "localhost" as a reserved target

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#470]
related https://github.com/ansible/receptor/pull/146

Receptor doesn't work if your `os.hostname` begins with "localhost", but it's very common for VMs and whatnot to be setup with localhost* as the hostname.

We should either strip this out, or rethink it to avoid that problem

**Comment by shanemcd** [comment]
I don't really see the problem here. I am fine with the current behavior.

**Comment by shanemcd** [comment]
I'm going to close this issue. I don't think it's unreasonable for receptor to expect a non-default hostname if you don't specify a node id.

**Comment by fosterseth** [comment]
@shanemcd 

I should have elaborated more on this. This is an issue even if you specify a nodeID, because we end up evoking receptor in a separate process when we start a work unit, and _that_ receptor does not have a node id

https://github.com/ansible/receptor/blob/fbba6530e5ae414b5e2301a7c1d587935360530b/pkg/workceptor/command.go#L232

We could just give that receptor a nodeID, either a random string, or even just whatever the parent nodeID is (because this receptor is never going to part of a networked mesh, the nodeID really doesn't matter)

```golang
diff --git a/pkg/workceptor/command.go b/pkg/workceptor/command.go
index 7c3d2d9..00a1fc6 100644
--- a/pkg/workceptor/command.go
+++ b/pkg/workceptor/command.go
@@ -229,11 +229,11 @@ func (cw *commandUnit) Start() error {
        level := logger.GetLogLevel()
        levelName, _ := logger.LogLevelToName(level)
        cw.UpdateBasicStatus(WorkStatePending, "Launching command runner", 0)
-       cmd := exec.Command(os.Args[0], "--log-level", levelName, "--command-runner",
+       cmd := exec.Command(os.Args[0], "--node", fmt.Sprintf("id=%s", cw.w.nc.NodeID()),
+               "--log-level", levelName, "--command-runner",
                fmt.Sprintf("command=%s", cw.command),
                fmt.Sprintf("params=%s", cw.Status().ExtraData.(*commandExtraData).Params),
                fmt.Sprintf("unitdir=%s", cw.UnitDir()))
-
        return cw.runCommand(cmd)
 }
```

Currently, if your hostname starts with `localhost`, jobs stay in pending state, and there isn't any indication what the problem is other than a single error message in the main receptor's stdout. I feel we should make this more transparent to the user somehow.

**Comment by shanemcd** [comment]
Ok, thank you for explaining. I have reopened #474 so we can do this there, but I do _not_ want to generate a random node id each time we start receptor.

**Comment by JustinGrote** [comment]
I was bit by this in ansible automation platform 2.5 containerized setup doing a setup and specifying localhost for everything rather than a specific hostname. My hosts were failing health checks and I had to track it to the podman logs for receptor.

`Error: node ID "localhost" is reserved`


Placing this here to help anyone else hopefully googling this in the future.
