### ISSUE TITLE
Websockets library

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#5]
The websockets back-end is currently using the `golang.org/x/net/websocket` library.  This library.s godoc page has a message "this package currently lacks some features found in alternative and more actively maintained WebSocket packages" and lacks features we care about, most significantly proxy server support.  It also looks like it's not easy to run a TLS server with this library.

The godoc page refers to two other libraries, `github.com/gorilla/websocket` and `nhooyr.io/websocket`.  We should pick whichever one has the needed functionality, and switch the websockets backend to it.

**Comment by squidboylan** [comment]
We're testing meshes using websocket backends in our automated testing
