### ISSUE TITLE
[CI] Ignore `sockets` from artifacts upload

### ISSUE THREAD

**Issue by thenets** [ansible/receptor#508]
Some pipelines are failing on `test` step due to an attempt to upload `socket` files.

Example:
https://github.com/ansible/receptor/runs/4287669792?check_suite_focus=true

cc: @shanemcd

**Comment by shanemcd** [comment]
@thenets is this still a problem?

**Comment by thenets** [comment]
@shanemcd I don't know. I have this issue here for the next week:
- https://github.com/ansible/receptor/issues/495

I can do it and at the same time check if this still happening.
