### ISSUE TITLE
RFE: Allow starting control service on a node with no tcp-listener or tcp-peer

### ISSUE THREAD

**Issue by kdelee** [ansible/receptor#518]
I noticed that while trying to start a receptor service with just a control service and a kubernetes work type that this was not possible.

I tried this:

Given config file `foo.yml`
```
---
- node:
    id: foo

- log-level:
    level: Debug

- control-service:
    service: control
    filename: /tmp/receptor.sock

- work-kubernetes:
    worktype: kube
    authmethod: kubeconfig
    allowruntimeauth: true
    allowruntimepod: true
    allowruntimeparams: true
```
I ran:
```
receptor -c foo.yml
```
Expected Result:
```
receptor -c ~/.receptor/k8swork.yml                   
INFO 2022/01/17 10:05:56 Running control service control
INFO 2022/01/17 10:05:56 Initialization complete
```
Then with the ability to submit kubernetes work units locally connecting to the socket.

Instead, the actual result was:

```
receptor -c foo.yml         

INFO 2022/01/17 10:04:11 Running control service control                      
WARNING 2022/01/17 10:04:11 Nothing to do - no backends are running.                          
Run receptor --help for command line instructions. 
```

It appears that one cannot start the control service w/o a tcp-peer or tcp-listener, even though we may be wanting to use receptor to just run the control service to then run kubernetes work units

**Comment by shanemcd** [comment]
Should already be possible if you add `- local-only:`
