### ISSUE TITLE
Recent change wastes 8 bytes per packet

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#525]
I just happened to be looking at the Netceptor code, and noticed: https://github.com/ansible/receptor/blob/2fb942e162a89be0a8793eb80691d0fa10249d08/pkg/netceptor/netceptor.go#L47

It appears that eight bytes have been added to the Netceptor protocol header, to store the string `svc-` for the to and from service name.  Note that these bytes are part of a fixed-length protocol header that must fit within the network MTU, normally 1500 bytes.  Adding eight bytes to this header makes Receptor half a percent slower (or worse for smaller MTUs), for no benefit that I can see.

If you want the services names to be displayed as "svc-whatever" then this should be handled in the API or the display code - it shouldn't be done at the protocol level.

CC @john-westcott-iv @shanemcd

**Comment by shanemcd** [comment]
Good call, I should have caught this. We'll get that change reverted. cc @john-westcott-iv

**Comment by shanemcd** [comment]
Reverted in https://github.com/ansible/receptor/pull/534
