### ISSUE TITLE
Container images are broken

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#537]
```
$ docker run quay.io/ansible/receptor:devel receptor --local-only
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/root/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.0/unsafe.go:20 +0x132
```

🔥

**Comment by shanemcd** [comment]
Happened after https://github.com/ansible/receptor/pull/535.

We may want to start running some smoke tests before pushing that image.

**Comment by kdelee** [comment]
This has broken `quay.io/ansible/awx-ee:latest` too https://github.com/ansible/awx-ee/issues/101

**Comment by shanemcd** [comment]
Image is fixed, will follow up with https://github.com/ansible/receptor/issues/539 and another PR that fixes the underlying problem.
