### ISSUE TITLE
Remote cancel and release in Workceptor

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#54]
Right now the Workceptor `work cancel` and `work release` commands are not aware of remote jobs.  Cancelling or releasing a job created by `work submit` will only cancel or release the local monitor associated with the job - it will keep running, and its files will continue to exist, on the remote node.  The `cancel` and `release` commands should be extended to operate on the remote node.  (One issue with this is defining what the behavior should be if the remote node is unreachable.)

**Comment by squidboylan** [comment]
@fosterseth added coverage for this to our CI that tests cancelling and verifies that when you `work release` on a remote job it deletes the files on the local and remote nodes
