### ISSUE TITLE
Example in documentation fails to run

### ISSUE THREAD

**Issue by benthomasson** [ansible/receptor#542]
Under basic usage on https://receptor.readthedocs.io/en/latest/# the example:

```
[](https://receptor.readthedocs.io/en/latest/#basic-usage)Basic usage

Run the following command in a terminal to start a node called foo,

receptor --node id=foo --local-only -- log-level Debug

The log shows the receptor node started successfully

INFO 2021/07/22 22:40:36 Initialization complete

```

Fails to run for me:

```
./receptor --node id=foo --local-only -- log-level Debug
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ghjm/cmdline.(*Cmdline).ParseAndRun(0xc0003613c0, 0xc00003a080, 0x6, 0x6, 0xc0000bde70, 0x3, 0x3, 0xc0000bde10, 0x1, 0x1, ...)
```

**Comment by benthomasson** [comment]
This appears to be due to an extra space in the example.

**Comment by shanemcd** [comment]
I'm reopening this because we should fix the underlying bug that caused receptor to panic.

**Comment by shanemcd** [comment]
@ghjm It looks like this may be a bug in your cmdline package. We can try to fix this and submit a PR unless you beat us to it.

**Comment by ghjm** [comment]
@shanemcd @fosterseth See https://github.com/ghjm/cmdline/pull/14.  Let me know if you're happy with this solution.

**Comment by Akasurde** [comment]
@shanemcd @fosterseth Can we close this as ghjm/cmdline#14 is merged? Thanks.

**Comment by shanemcd** [comment]
I'll leave this open until we bump the dependency. @ghjm Mind pinging us here when you cut a new release?

**Comment by ghjm** [comment]
Done, https://github.com/ghjm/cmdline/releases/tag/v0.1.2

**Comment by fosterseth** [comment]
receptor now uses 0.1.2

```
[sbf@fedora sockceptor]$ ./receptor --node id=foo --local-only -- log-level Debug
Error: command error: unknown config type
```

no longer panics, closing this issue
