### ISSUE TITLE
Broken pipeline: Container CI

### ISSUE THREAD

**Issue by thenets** [ansible/receptor#575]
There's a broken pipeline on GitHub Actions, probably due to some Python or Python lib upgrade change.

## Error

I faced this issue here:

- https://github.com/ansible/receptor/pull/559
- https://github.com/ansible/receptor/runs/5485928827?check_suite_focus=true

```java
Run make container
  make container
  shell: /usr/bin/bash -e {0}
error in setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'.'"
error in setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'.'"
make: *** [Makefile:115: receptorctl/dist/receptorctl--py3-none-any.whl] Error 1
Error: Process completed with exit code [2](https://github.com/ansible/receptor/runs/5485928827?check_suite_focus=true#step:3:2).
```

Looks like this issue came from:
- `VERSION` variable:
  - `VERSION := $(shell cd receptorctl && python3 setup.py --version)`
- Make commands:
  - `make receptorctl_wheel`
  - `make receptorctl_sdist`

## How to reproduce

I have a fresh Fedora 35 Workstation installation and I can get the same error that shows in the GitHub Actions.

## Additional information

I believe we should get the version from `git` commands and avoid any Python dependency on the `Makefile`. Additionally, the build process could run on containers only to avoid this kind of issue. Instead of building the files outside the container and copying the package to the image, we can create a `build` stage in the `Dockerfile`.

**Comment by shanemcd** [comment]
It seems like the problem was introduced in your PR. Let's keep this conversation over there.

**Comment by thenets** [comment]
Thanks, Shane!
