### ISSUE TITLE
Work results stream sometimes exits before all data has been received

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#597]
### Background

We've seen several reports of AWX jobs entering the "error" state even though the playbook actually runs to completion.

See:

- https://github.com/ansible/ansible-runner/issues/998
- https://github.com/ansible/awx/issues/11511

There may be more. If I find them I'll update the list above.

----

### The problem

AWX uses Receptor to launch remote work. We utilize ansible-runner's [streaming interface](https://github.com/ansible/ansible-runner/blob/d467662f585f5bb6ed2c5e8d57f130772760031a/ansible_runner/streaming.py) to convert both the job's payload and results into a format that can be delivered over a network.

The flow is something like this:

- [AWX creates a `socketpair`](https://github.com/ansible/awx/blob/8a5fd115061688d8e567dc5f11482baa0617e6e9/awx/main/tasks/receptor.py#L287)
- [The job's payload is written to the left side of the socketpair](https://github.com/ansible/awx/blob/8a5fd115061688d8e567dc5f11482baa0617e6e9/awx/main/tasks/receptor.py#L297)
- [The right side of the socketpair is passed off to receptor](https://github.com/ansible/awx/blob/8a5fd115061688d8e567dc5f11482baa0617e6e9/awx/main/tasks/receptor.py#L300)
- [The results of the job are requested from Receptor. This returns a socket to read from.](https://github.com/ansible/awx/blob/8a5fd115061688d8e567dc5f11482baa0617e6e9/awx/main/tasks/receptor.py#L332)
- [We pass the results socket to ansible-runner so it can process the results coming back](https://github.com/ansible/awx/blob/8a5fd115061688d8e567dc5f11482baa0617e6e9/awx/main/tasks/receptor.py#L340)
- [Work results are mostly newline delimited json, with a length-prefixed header at the end of the stream containing b64 encoded zip data that unpacks the job's artifacts.](https://github.com/ansible/ansible-runner/blob/d467662f585f5bb6ed2c5e8d57f130772760031a/ansible_runner/streaming.py#L243-L258)

Now with this context, let's take another look at https://github.com/ansible/ansible-runner/issues/998. You can see that for some reason, the data it's trying to decode is not valid base64 data.

With that in mind, I added some debug logging to see what was going on when ansible-runner blew up. What I found was that subsequent reads from the socket were returning an empty byte string:

```
>>> newline = self._input.readline()
None
>>> newline
b''
```

If you go and try it out, this is simply the behavior when trying to read from a `socket.makefile()` after the writer has closed the connection.

So, why is the connection getting closed?

You can see that Receptor closes the connection when it thought all results had been written to a channel whose contents were being streamed back to the client:

https://github.com/ansible/receptor/blob/5f89364913d78a84cd69a70f3b82c28822d956a5/pkg/workceptor/controlsvc.go#L427-L436

If we look inside `GetResults`, it's a goroutine writing to the channel being read and sent to the client. The loop ejects when it sees an EOF event, if the work unit is complete, it considers the stream to finished too:

https://github.com/ansible/receptor/blob/5f89364913d78a84cd69a70f3b82c28822d956a5/pkg/workceptor/workceptor.go#L568

Let's add some debug logging to inspect the variables when this condition hits:

```diff
bash-4.4$ git diff pkg/workceptor/workceptor.go 
bash-4.4$ git diff pkg/workceptor/workceptor.go 
diff --git a/pkg/workceptor/workceptor.go b/pkg/workceptor/workceptor.go
index 41bde23..f4fdd38 100644
--- a/pkg/workceptor/workceptor.go
+++ b/pkg/workceptor/workceptor.go
@@ -575,6 +575,10 @@ func (w *Workceptor) GetResults(ctx context.Context, unitID string, startPos int
                                unitStatus := unit.Status()
                                if IsComplete(unitStatus.State) && stdoutSize >= unitStatus.StdoutSize && filePos >= unitStatus.StdoutSize {
                                        logger.Debug("Stdout complete - closing channel for: %s \n", unitID)
+                                       logger.Debug("filePos for %s: %d", unitID, filePos)
+                                       logger.Debug("unit.Status().StdoutSize for %s: %d", unitID, unit.Status().StdoutSize)
+                                       logger.Debug("stdoutSize %s: %d", unitID, stdoutSize)
+                                       logger.Debug("Last bytes for %s: %d", unitID, lastBytes)
 
                                        return
                                }
```

For a job that blew up, I saw:

```
DEBUG 2022/04/20 15:27:25 Stdout complete - closing channel for: EIlF5ofA
DEBUG 2022/04/20 15:27:25 filePos for EIlF5ofA: 20394593
DEBUG 2022/04/20 15:27:25 unit.Status().StdoutSize for EIlF5ofA: 20418334
DEBUG 2022/04/20 15:27:25 stdoutSize EIlF5ofA: 20418334
```

Wait... why is `filePos` less than `stdoutSize`?

If you look closely, the file size is obtained directly above the suspect conditional:

https://github.com/ansible/receptor/blob/a96b855b1a1b67a097fbcc10ff8d4025b85ed1b1/pkg/workceptor/workceptor.go#L567

So now we're getting to the root of the problem:

- The loop breaks because we saw an EOF event.
- More data was still coming across the network
- In between the loop breaking and where we are stat'ing the file, the stdout file continued to grow slightly.

Another potential bug that may be another race condition waiting to bite us is the fact that we make 2 calls to `unit.Status()` on the same line

https://github.com/ansible/receptor/blob/a96b855b1a1b67a097fbcc10ff8d4025b85ed1b1/pkg/workceptor/workceptor.go#L568

Putting all of these pieces together, the fix looks something like this:

```diff
bash-4.4$ git diff pkg/workceptor/workceptor.go 
diff --git a/pkg/workceptor/workceptor.go b/pkg/workceptor/workceptor.go
index a38594b..41bde23 100644
--- a/pkg/workceptor/workceptor.go
+++ b/pkg/workceptor/workceptor.go
@@ -572,7 +572,8 @@ func (w *Workceptor) GetResults(ctx context.Context, unitID string, startPos int
                        }
                        if err == io.EOF {
                                stdoutSize := stdoutSize(unitdir)
-                               if IsComplete(unit.Status().State) && stdoutSize >= unit.Status().StdoutSize {
+                               unitStatus := unit.Status()
+                               if IsComplete(unitStatus.State) && stdoutSize >= unitStatus.StdoutSize && filePos >= unitStatus.StdoutSize {
                                        logger.Debug("Stdout complete - closing channel for: %s \n", unitID)
 
                                        return
```

**Comment by stanislav-zaprudskiy** [comment]
I just tried to reproduce https://github.com/ansible/ansible-runner/issues/998#issuecomment-1088947800 using the latest binary `1.2.0+gd5c6315` in both AWX' `ee` container and EE Pod container, but AWX' `task` container still throws the same `zipfile.BadZipFile: File is not a zip file` error.

**Comment by hesmithrh** [comment]
related PR: https://github.com/ansible/receptor/pull/600 ?
