### ISSUE TITLE
receptor --version shows + g instead of version

### ISSUE THREAD

**Issue by MalfuncEddie** [ansible/receptor#604]
In the latest release when compiling the version is +g . 

```
make receptor 
./receptor --version
+g
```

**Comment by shanemcd** [comment]
Please ensure you have git installed:

https://github.com/ansible/receptor/blob/d5c63156090c4d47bf977b0ff6c269dc90ee12a2/Makefile#L5

**Comment by MalfuncEddie** [comment]
tnx,
I had it installed but was using the tar.gz version

**Comment by eqrx** [comment]
@MalfuncEddie if your are using go v1.18 (and the receptor binary you have was built with it) you can execute `go version <path to receptor binary>` to get the source information without the need to have git installed
