### ISSUE TITLE
Allow for providing receptor-specific parameters when starting units of work

### ISSUE THREAD

**Issue by shanemcd** [ansible/receptor#78]
As I was reviewing https://github.com/project-receptor/receptor/pull/71, it occurred to me that we'll need a way to provide a kubeconfig / pod name at runtime.

Spoke with @ghjm about this briefly this morning. He's going to noodle on it.

**Comment by ghjm** [comment]
Maybe what we really want here is the ability to start and stop workceptor listeners at runtime, the way you can start and stop `net.Conn` listeners at runtime.  Having to restart the entire Receptor node to change a worker parameter is kind of an anti-pattern.

**Comment by ghjm** [comment]
https://github.com/project-receptor/receptor/pull/146 should unblock progress on this

**Comment by ghjm** [comment]
I think we can close this.  Putting it in needs_test so @squidboylan can given an opinion of whether we need to do any verification or anything.

**Comment by squidboylan** [comment]
We discussed this and it's not really related to what #213 is testing, but @fosterseth has added some tests that use the `tlsclient` json fields which we've discussed is testing what this issue is about.
