### ISSUE TITLE
Make this work with Ansible Runner

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#8]
Supporting Ansible Runner may be as simple as having the right command-line parameters and stdin, running in `--json` mode, and passing the output as Receptor stdout.  The existing `--via-receptor` parameter in Runner expects to import old Receptor, so this should be modified.

The current Receptor plugin in Ansible Runner is incomplete anyway.  It supports passing job results to stout, but does not call the Python callbacks on the originating side.  We should make the implementation more transparent, so a Python user of Runner doesn't have to change their API at all to run jobs through Receptor.

**Comment by AlanCoding** [comment]
Link https://github.com/ansible/ansible-runner/pull/505

Several bits of history here:

 - that PR is removing the old plugin as this issue suggests
 - some new flags were toyed around with like `--worker-in` and `--worker-out`, but these have been removed
 - the updated commands
    - write lines of JSON to stdout in the case of `ansible-runner transmit`
    - both read and write lines of JSON from and to stdout in the case of `ansible-runner worker`
    - read lines of JSON from stdout in the case of `ansible-runner process`
 - the private data directory is bundled into a zip file and sent by `transmit` to `worker`

In terms of how to configure a receptor mesh to use this, we have a controller and a worker. The controller needs to say "hey worker, run `ansible-runner worker` and start streaming from me". Then `worker` will know how to interpret that stream and starts a subprocess running `ansible-playbook`, podman, or whatever. Then `process` is probably self-obvious, but I will have more questions after I understand the capabilities of the runner mesh.
