### ISSUE TITLE
receptorctl --help requires --socket to be defined

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#80]
```
[sfoster@localhost sockceptor]$ receptorctl work --help
Error: missing parameter: socket
```

**Comment by fosterseth** [comment]
@ghjm 

there is this solution, as described here https://stackoverflow.com/a/55821551

basically the idea is to override the `parse_args()` method of the `click.Group` class -- in the presence of `--help` it will set required parameters to false

we would add this to the top of cli.py

```python
class IgnoreRequiredWithHelp(click.Group):
    def parse_args(self, ctx, args):
        try:
            return super(IgnoreRequiredWithHelp, self).parse_args(ctx, args)
        except click.MissingParameter as exc:
            if '--help' not in args:
                raise

            # remove the required params so that help can display
            for param in self.params:
                param.required = False
            return super(IgnoreRequiredWithHelp, self).parse_args(ctx, args)
```

Alternatively, we can just remove the `required=True` parameter, but then the `--help` doesn't label it with `required`.

**Comment by ghjm** [comment]
I like the IgnoreRequiredWithHelp solution better.  I'd rather fail early if we don't have a socket and the user is trying to do a real command.  (Aren't you supposed to be on PTO?)
