### ISSUE TITLE
Kube Reconnect Support not detected on k3s 1.27.2+k3s1

### ISSUE THREAD

**Issue by Klaas-** [ansible/receptor#801]
Hi,
this is a follow up to https://github.com/ansible/awx/issues/14057 and https://github.com/ansible/receptor/pull/683

I am running k3s:
```
# k3s --version
k3s version v1.27.2+k3s1 (213d7ad4)
go version go1.20.4
# kubectl version -o yaml
clientVersion:
  buildDate: "2023-05-26T22:14:11Z"
  compiler: gc
  gitCommit: 213d7ad499e166290872f51c63d8eaa2f1fe78b3
  gitTreeState: clean
  gitVersion: v1.27.2+k3s1
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-05-26T22:14:11Z"
  compiler: gc
  gitCommit: 213d7ad499e166290872f51c63d8eaa2f1fe78b3
  gitTreeState: clean
  gitVersion: v1.27.2+k3s1
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64

```

It seems the automatic detection in https://github.com/ansible/receptor/blob/4addde85f132cc555331041e9a6f7963519c542c/pkg/workceptor/kubernetes.go#L763-L797 is not working for me. With the latest AWX (22.3.0) I need to set the RECEPTOR_KUBE_SUPPORT_RECONNECT variable manually in my awx spec.

**Comment by shanemcd** [comment]
I believe we ended up disabling it by default due to some issues we found with certain k8s environments. @fosterseth @TheRealHaoLiu may be able to provide more details.

**Comment by Klaas-** [comment]
Yeah @shanemcd that is correct :) I did not see that change ...
https://github.com/ansible/receptor/blob/4addde85f132cc555331041e9a6f7963519c542c/pkg/workceptor/kubernetes.go#L811-L813

I'll close this :)
