### ISSUE TITLE
Kubernetes worker does not preserve state on Receptor restart

### ISSUE THREAD

**Issue by ghjm** [ansible/receptor#86]
If you launch a Kubernetes job and then restart Receptor, it loses track of the job - stdout is never made available, the job is not cancellable, etc.  To fix this we need to do a rewrite of Workceptor to allow storing worker-specific data in the status file, most notably the pod ID.  This Workceptor rewrite is also likely needed for https://github.com/project-receptor/receptor/issues/78.

**Comment by squidboylan** [comment]
looks like the stdout we get in this scenario is incorrect, see https://github.com/project-receptor/receptor/pull/257 for my test. It looks like the kubernetes job stdout is:

```
1
1
2
3
4
5
```
so the first line is being duplicated (im guessing that's where the restart is happening).
